spring.application.name=spring

logging.level.chat.sda.spring.service=INFO
logging.level.chat.sda.spring.controller=INFO
logging.level.root=ERROR

logging.pattern.console=[%level] %msg%n

node.id=${NODE_ID:1}
node.host=${NODE_HOST:192.168.1.107}
server.port=${PORT:60001}
simulation.delay.enabled=${DELAY:false}
node.peers=${NODE_PEERS:1:192.168.1.107:60001,2:192.168.1.107:60002,3:192.168.1.64:60003,4:192.168.1.107:60004}
#java -jar peer.jar --node.id=1 --server.port=60001 --node.host=192.168.1.107 --simulation.delay.enabled=true
#java -jar peer.jar --node.id=2 --server.port=60002 --node.host=192.168.1.107 --simulation.delay.enabled=false
#java -jar peer.jar --node.id=3 --server.port=60003 --node.host=192.168.1.64 --simulation.delay.enabled=false
#java -jar peer.jar --node.id=4 --server.port=60004 --node.host=192.168.1.107 --simulation.delay.enabled=false
#npm run dev -- --host