spring.application.name=spring
node.id=${NODE_ID:1}
node.host=${NODE_HOST:localhost}
server.port=${PORT:60001}
node.peers=${NODE_PEERS:1:localhost:60001,2:localhost:60002,3:localhost:60003,4:localhost:60004}

